[databases]
# Format: nama_db_luar = host=nama_container port=5432 dbname=nama_db_asli
* = host=postgres-db port=5432

[pgbouncer]
listen_addr = *
listen_port = 5432
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction

# ================================
# ENTERPRISE TUNING & RAM SAVER
# ================================
max_client_conn = 1000
default_pool_size = 50
reserve_pool_size = 10
reserve_pool_timeout = 5

# Mencegah data bocor antar transaksi (sangat penting untuk mode transaction)
server_reset_query = DISCARD ALL

# Mematikan log yang tidak perlu agar CPU & Harddisk tidak tersiksa
log_connections = 0
log_disconnections = 0