listen_addresses = '*'
# Koneksi dibatasi! Biarkan PgBouncer yang menampung ribuan koneksi dari luar
max_connections = 70

# Tuning Memori
shared_buffers = 256MB
work_mem = 16MB
maintenance_work_mem = 64MB
effective_cache_size = 768MB

# Lokasi Waktu
log_timezone = 'Asia/Jakarta'
timezone = 'Asia/Jakarta'

# Standar Keamanan Enkripsi Password (bawaan PG 16)
password_encryption = scram-sha-256