# /opt/devops/00-gateway/nginx/conf.d/00-default.conf
# untuk memblok/tendang setiap akses ip local/public

# ==========================================
# 1. TONG SAMPAH UNTUK HTTP BIASA
# ==========================================
server {
    listen 80 default_server;
    # Tambahkan port HTTP lain di sini jika ada, contoh:
    # listen 8080 default_server; 
    
    server_name _;
    return 444; # Putus koneksi
}

# ==========================================
# 2. TONG SAMPAH UNTUK HTTPS / SSL
# ==========================================
server {
    listen 443 ssl default_server;
    listen 1337 ssl default_server;
    listen 8003 ssl default_server;
    listen 8069 ssl default_server;
    listen 8070 ssl default_server;
    listen 8443 ssl default_server;
    # (Tambahkan terus ke bawah sesuai port SSL yang Anda buka di docker-compose Gateway)

    # TAMBAHKAN BARIS INI AGAR SERAGAM:
    http2 on;
    server_name _;
    # Langsung tolak koneksi dari IP langsung agar CPU tidak capek mikir
    ssl_reject_handshake on;
}