# 00-gateway/nginx/conf.d/ridhoreynaldo-com.conf
server {
    listen 80;
    server_name ridhoreynaldo.com www.ridhoreynaldo.com;

    include /etc/nginx/snippets/acme-challenge.conf;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name ridhoreynaldo.com www.ridhoreynaldo.com;

    # File yang dipetakan dari volume ./ssl:/etc/nginx/ssl:ro
    ssl_certificate /etc/nginx/ssl/ridhoreynaldo-com/ridhoreynaldo.crt;
    ssl_certificate_key /etc/nginx/ssl/ridhoreynaldo-com/ridhoreynaldo.key;

    include /etc/nginx/snippets/security-headers.conf;

    resolver 127.0.0.11 valid=30s;
    set $upstream_app http://web_ridhoreynaldo:8000;

    location / {
        limit_req zone=req_limit_per_ip burst=20 nodelay;
        limit_conn conn_limit_per_ip 50;

        include /etc/nginx/snippets/proxy.conf;
        proxy_set_header Host $host;

        proxy_pass $upstream_app;
    }
}
