server {
    listen 80;
    server_name ridhoreynaldo.com www.ridhoreynaldo.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name ridhoreynaldo.com www.ridhoreynaldo.com;

    # File yang dipetakan dari volume ./ssl:/etc/nginx/ssl:ro
    ssl_certificate /etc/nginx/ssl/ridhoreynaldo-com/ridhoreynaldo.crt;
    ssl_certificate_key /etc/nginx/ssl/ridhoreynaldo-com/ridhoreynaldo.key;

    resolver 127.0.0.11 valid=30s;
    set $upstream_app http://web_ridhoreynaldo:8000;

    location / {
        proxy_pass $upstream_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}