name: Sync DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: |
          cd /opt/devops-2
          git pull --ff-only origin main